; ALLOWS ONE TO START THE APPLICATION WITH RUN
; SYS 2064
*=$0801 
         BYTE $0C, $8, $0A, $00, $9E, $20, $32, $30, $36, $34, $00, $00, $00, $00, $00

; PLAN:
; * SCREEN SHALL DISPLAY FULL SIZED MAZE MADE OF BACKGROUND CHARACTERS
;       ** BACKGROUND CHARACTERS SHALL BE MULTICOLOR, WITH FLOOR TEXTURE WHICH DOES NOT TRIGGER COLLISION
;       ** MAZE WALLS WILL BE OF COLORS THAT WILL TRIGGER THE COLLISION
; * THERE SHALL BE A JOYSTICK CONTROLLABLE SPRITE WHICH DOES NOT GO THOUGHT WALLS
; * THERE SHALL BE A STATIONARY SPRITE IN THE MIDDLE OF THE MAZE
;       ** CONTROLLABLE SPRITE SHALL NOT GO THOUGH THE STATIONARY SPRITE
; * MAZE AND SPRITES SHALL DISPLAY STRAIGHT FROM ABOVE

MAIN    
        JMP MAIN
